# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/voice_engine/out
.PHONY: all
all:
	$(MAKE) -C ../.. pstn_serv_arm_gyp voice_engine_core voe_cmd_test voe_auto_test voice_engine_unittests pstn_cmd_test
