# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := buildbot_tests_scripts
### Generated for copy rule.
$(builddir)/buildbot_tests.py: TOOLSET := $(TOOLSET)
$(builddir)/buildbot_tests.py: webrtc/test/buildbot_tests.py FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/buildbot_tests.py
$(builddir)/run_audio_test.py: TOOLSET := $(TOOLSET)
$(builddir)/run_audio_test.py: tools/e2e_quality/audio/run_audio_test.py FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/run_audio_test.py
$(builddir)/perf/__init__.py: TOOLSET := $(TOOLSET)
$(builddir)/perf/__init__.py: tools/perf/__init__.py FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/perf/__init__.py
$(builddir)/perf/perf_utils.py: TOOLSET := $(TOOLSET)
$(builddir)/perf/perf_utils.py: tools/perf/perf_utils.py FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/perf/perf_utils.py
trunk_webrtc_test_test_gyp_buildbot_tests_scripts_target_copies = $(builddir)/buildbot_tests.py $(builddir)/run_audio_test.py $(builddir)/perf/__init__.py $(builddir)/perf/perf_utils.py

### Rules for final target.
# Build our special outputs first.
$(obj).target/webrtc/test/buildbot_tests_scripts.stamp: | $(trunk_webrtc_test_test_gyp_buildbot_tests_scripts_target_copies)

# Preserve order dependency of special output on deps.
$(trunk_webrtc_test_test_gyp_buildbot_tests_scripts_target_copies): | 

$(obj).target/webrtc/test/buildbot_tests_scripts.stamp: TOOLSET := $(TOOLSET)
$(obj).target/webrtc/test/buildbot_tests_scripts.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/webrtc/test/buildbot_tests_scripts.stamp
# Add target alias
.PHONY: buildbot_tests_scripts
buildbot_tests_scripts: $(obj).target/webrtc/test/buildbot_tests_scripts.stamp

# Add target alias to "all" target.
.PHONY: all
all: buildbot_tests_scripts

