# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := test_support_main_threaded_mac
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-B$(builddir)/../../third_party/gold \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-B$(builddir)/../../third_party/gold \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a: LIBS := $(LIBS)
$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a: TOOLSET := $(TOOLSET)
$(obj).target/webrtc/test/libtest_support_main_threaded_mac.a:  FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/webrtc/test/libtest_support_main_threaded_mac.a
# Add target alias
.PHONY: test_support_main_threaded_mac
test_support_main_threaded_mac: $(obj).target/webrtc/test/libtest_support_main_threaded_mac.a

# Add target alias to "all" target.
.PHONY: all
all: test_support_main_threaded_mac

