# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/common_audio/out
.PHONY: all
all:
	$(MAKE) -C ../.. signal_processing vad resampler signal_processing_unittests resampler_unittests vad_unittests
