# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/tools/out
.PHONY: all
all:
	$(MAKE) -C ../.. frame_editing_lib command_line_parser frame_editor video_quality_analysis tools_unittests rgba_to_i420_converter psnr_ssim_analyzer frame_analyzer
