FIND_PATH(MEDIASTREAMER_INCLUDE_DIR  NAMES mediastreamer2/mscommon.h ortp/ortp.h 
			speex/speex.h ogg/ogg.h gsm/gsm.h
			PATHS   /phone/include/ )
FIND_LIBRARY(MEDIASTREAMER_LIBRARY NAMES mediastreamer ortp gsm ogg speex speexdsp
			PATHS "/phone/lib"   )
IF (MEDIASTREAMER_INCLUDE_DIR AND MEDIASTREAMER_LIBRARY)
	SET(MEDIASTREAMER_FOUND TRUE)
	MESSAGE(STATUS "SET MEDIASTREAMER_FOUND TRUE")
ENDIF(MEDIASTREAMER_INCLUDE_DIR AND MEDIASTREAMER_LIBRARY)

IF(MEDIASTREAMER_FOUND)
	IF(NOT MEDIASTREAMER_FIND_QUIETLY)
		MESSAGE(STATUS "Found MEDIASTREAMER: ${MEDIASTREAMER_LIBRARY}")
	ENDIF(NOT MEDIASTREAMER_FIND_QUIETLY)
ELSE (MEDIASTREAMER_FOUND)
	IF(MEDIASTREAMER_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find MEDIASTREAMER library")
	ENDIF(MEDIASTREAMER_FIND_REQUIRED)
ENDIF(MEDIASTREAMER_FOUND)

