#cmake -DCMAKE_INSTALL_PREFIX=/usr ..
FIND_PATH(PSTNSERV_INCLUDE_DIR  NAMES mymediastream.h padtophone.h 
			PATHS "/phone/include/pstnserv"  ${PROJECT_SOURCE_DIR}/include )
FIND_LIBRARY(PSTNSERV_LIBRARY NAMES pstnserv PATHS "/phone/lib" 
	  "${PROJECT_SOURCE_DIR}/build/lib"  ./lib)
IF (PSTNSERV_INCLUDE_DIR AND PSTNSERV_LIBRARY)
	SET(PSTNSERV_FOUND TRUE)
	MESSAGE(STATUS "SET PSTNSERV_FOUND TRUE")
ENDIF(PSTNSERV_INCLUDE_DIR AND PSTNSERV_LIBRARY)

IF(PSTNSERV_FOUND)
	IF(NOT PSTNSERV_FIND_QUIETLY)
		MESSAGE(STATUS "Found PSTNSERV: ${PSTNSERV_LIBRARY}")
	ENDIF(NOT PSTNSERV_FIND_QUIETLY)
ELSE (PSTNSERV_FOUND)
	IF(PSTNSERV_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find PSTNSERV library")
	ENDIF(PSTNSERV_FIND_REQUIRED)
ENDIF(PSTNSERV_FOUND)
