# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := audio_coding_module
DEFS_Debug := \
	'-DWEBRTC_SVNREVISION="Unavailable(issue687)"' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DWEBRTC_LOGGING' \
	'-DWEBRTC_ARCH_ARM' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DWEBRTC_CODEC_OPUS' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Woverloaded-virtual \
	-Wno-abi

INCS_Debug := \
	-Iwebrtc \
	-I. \
	-I. \
	-Iwebrtc/modules/audio_coding/main/interface \
	-Iwebrtc/modules/interface \
	-Iwebrtc/modules/audio_coding/codecs/cng/include \
	-Iwebrtc/modules/audio_coding/codecs/g711/include \
	-Iwebrtc/modules/audio_coding/codecs/g722/include \
	-Iwebrtc/modules/audio_coding/codecs/ilbc/interface \
	-Iwebrtc/modules/audio_coding/codecs/isac/main/interface \
	-Iwebrtc/modules/audio_coding/codecs/isac/fix/interface \
	-Iwebrtc/modules/audio_coding/codecs/pcm16b/include \
	-Iwebrtc/modules/audio_coding/neteq/interface \
	-Iwebrtc/common_audio/resampler/include \
	-Iwebrtc/common_audio/signal_processing/include \
	-Iwebrtc/common_audio/vad/include \
	-Iwebrtc/system_wrappers/interface \
	-I/usr/local/arm/4.4.1/arm-none-linux-gnueabi/libc/usr/include

DEFS_Release := \
	'-DWEBRTC_SVNREVISION="Unavailable(issue687)"' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DWEBRTC_LOGGING' \
	'-DWEBRTC_ARCH_ARM' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DWEBRTC_CODEC_OPUS' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Woverloaded-virtual \
	-Wno-abi

INCS_Release := \
	-Iwebrtc \
	-I. \
	-I. \
	-Iwebrtc/modules/audio_coding/main/interface \
	-Iwebrtc/modules/interface \
	-Iwebrtc/modules/audio_coding/codecs/cng/include \
	-Iwebrtc/modules/audio_coding/codecs/g711/include \
	-Iwebrtc/modules/audio_coding/codecs/g722/include \
	-Iwebrtc/modules/audio_coding/codecs/ilbc/interface \
	-Iwebrtc/modules/audio_coding/codecs/isac/main/interface \
	-Iwebrtc/modules/audio_coding/codecs/isac/fix/interface \
	-Iwebrtc/modules/audio_coding/codecs/pcm16b/include \
	-Iwebrtc/modules/audio_coding/neteq/interface \
	-Iwebrtc/common_audio/resampler/include \
	-Iwebrtc/common_audio/signal_processing/include \
	-Iwebrtc/common_audio/vad/include \
	-Iwebrtc/system_wrappers/interface \
	-I/usr/local/arm/4.4.1/arm-none-linux-gnueabi/libc/usr/include

OBJS := \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_amr.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_amrwb.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_celt.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_cng.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_codec_database.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_dtmf_detection.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_dtmf_playout.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_g722.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_g7221.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_g7221c.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_g729.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_g7291.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_generic_codec.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_gsmfr.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_ilbc.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_isac.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_neteq.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_opus.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_speex.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_pcm16b.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_pcma.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_pcmu.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_red.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/acm_resampler.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/audio_coding_module.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_coding/main/source/audio_coding_module_impl.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-B$(builddir)/../../third_party/gold \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-B$(builddir)/../../third_party/gold \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	

$(obj).target/webrtc/modules/libaudio_coding_module.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/webrtc/modules/libaudio_coding_module.a: LIBS := $(LIBS)
$(obj).target/webrtc/modules/libaudio_coding_module.a: TOOLSET := $(TOOLSET)
$(obj).target/webrtc/modules/libaudio_coding_module.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/webrtc/modules/libaudio_coding_module.a
# Add target alias
.PHONY: audio_coding_module
audio_coding_module: $(obj).target/webrtc/modules/libaudio_coding_module.a

# Add target alias to "all" target.
.PHONY: all
all: audio_coding_module

