# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := rtp_rtcp_unittests
DEFS_Debug := \
	'-DWEBRTC_SVNREVISION="Unavailable(issue687)"' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DWEBRTC_LOGGING' \
	'-DWEBRTC_ARCH_ARM' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Woverloaded-virtual \
	-Wno-abi

INCS_Debug := \
	-Iwebrtc \
	-I. \
	-I. \
	-Iwebrtc \
	-Iwebrtc/test \
	-Iwebrtc/modules/rtp_rtcp/interface \
	-Iwebrtc/modules/interface \
	-Itesting/gmock/include \
	-Itesting/gtest/include \
	-Iwebrtc/system_wrappers/interface \
	-I/usr/local/arm/4.4.1/arm-none-linux-gnueabi/libc/usr/include

DEFS_Release := \
	'-DWEBRTC_SVNREVISION="Unavailable(issue687)"' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_DEFAULT_RENDER_THEME=1' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DUSE_NSS=1' \
	'-DENABLE_ONE_CLICK_SIGNIN' \
	'-DGTK_DISABLE_SINGLE_INCLUDES=1' \
	'-DENABLE_REMOTING=1' \
	'-DENABLE_WEBRTC=1' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DENABLE_INPUT_SPEECH' \
	'-DENABLE_NOTIFICATIONS' \
	'-DENABLE_GPU=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DENABLE_TASK_MANAGER=1' \
	'-DENABLE_EXTENSIONS=1' \
	'-DENABLE_PLUGIN_INSTALLATION=1' \
	'-DENABLE_PLUGINS=1' \
	'-DENABLE_SESSION_SERVICE=1' \
	'-DENABLE_THEMES=1' \
	'-DENABLE_BACKGROUND=1' \
	'-DENABLE_AUTOMATION=1' \
	'-DENABLE_GOOGLE_NOW=1' \
	'-DENABLE_LANGUAGE_DETECTION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_CAPTIVE_PORTAL_DETECTION=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DWEBRTC_LOGGING' \
	'-DWEBRTC_ARCH_ARM' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_THREAD_RR' \
	'-DUNIT_TEST' \
	'-DGTEST_HAS_RTTI=0' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-pthread \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Woverloaded-virtual \
	-Wno-abi

INCS_Release := \
	-Iwebrtc \
	-I. \
	-I. \
	-Iwebrtc \
	-Iwebrtc/test \
	-Iwebrtc/modules/rtp_rtcp/interface \
	-Iwebrtc/modules/interface \
	-Itesting/gmock/include \
	-Itesting/gtest/include \
	-Iwebrtc/system_wrappers/interface \
	-I/usr/local/arm/4.4.1/arm-none-linux-gnueabi/libc/usr/include

OBJS := \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/test/testAPI/test_api.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/test/testAPI/test_api_audio.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/test/testAPI/test_api_nack.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/test/testAPI/test_api_rtcp.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/test/testAPI/test_api_video.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/fec_test_helper.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/nack_rtx_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/producer_fec_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/receiver_fec_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtcp_format_remb_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtcp_sender_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtcp_receiver_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_fec_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_format_vp8_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_format_vp8_test_helper.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_packet_history_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_payload_registry_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_utility_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_header_extension_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/rtp_sender_unittest.o \
	$(obj).target/$(TARGET)/webrtc/modules/rtp_rtcp/source/vp8_partition_aggregator_unittest.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/webrtc/modules/librtp_rtcp.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/webrtc/test/libtest_support_main.a $(obj).target/webrtc/system_wrappers/source/libsystem_wrappers.a $(obj).target/webrtc/modules/libremote_bitrate_estimator.a $(obj).target/webrtc/modules/libpaced_sender.a $(obj).target/testing/gtest_prod.stamp $(obj).target/webrtc/test/libtest_support.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-B$(builddir)/../../third_party/gold \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot

LDFLAGS_Release := \
	-Wl,-z,now \
	-Wl,-z,relro \
	-pthread \
	-Wl,-z,noexecstack \
	-fPIC \
	-B$(builddir)/../../third_party/gold \
	--sysroot=/root/newdisk1/webrtc_no_peerconnection/trunk/arm-sysroot \
	-Wl,-O1 \
	-Wl,--as-needed \
	-Wl,--gc-sections

LIBS := \
	 \
	-lrt

$(builddir)/rtp_rtcp_unittests: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/rtp_rtcp_unittests: LIBS := $(LIBS)
$(builddir)/rtp_rtcp_unittests: LD_INPUTS := $(OBJS) $(obj).target/webrtc/modules/librtp_rtcp.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/webrtc/test/libtest_support_main.a $(obj).target/webrtc/system_wrappers/source/libsystem_wrappers.a $(obj).target/webrtc/modules/libremote_bitrate_estimator.a $(obj).target/webrtc/modules/libpaced_sender.a $(obj).target/webrtc/test/libtest_support.a
$(builddir)/rtp_rtcp_unittests: TOOLSET := $(TOOLSET)
$(builddir)/rtp_rtcp_unittests: $(OBJS) $(obj).target/webrtc/modules/librtp_rtcp.a $(obj).target/testing/libgmock.a $(obj).target/testing/libgtest.a $(obj).target/webrtc/test/libtest_support_main.a $(obj).target/webrtc/system_wrappers/source/libsystem_wrappers.a $(obj).target/webrtc/modules/libremote_bitrate_estimator.a $(obj).target/webrtc/modules/libpaced_sender.a $(obj).target/webrtc/test/libtest_support.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/rtp_rtcp_unittests
# Add target alias
.PHONY: rtp_rtcp_unittests
rtp_rtcp_unittests: $(builddir)/rtp_rtcp_unittests

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/rtp_rtcp_unittests

